apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-lb
  labels:
    app: hello-world-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8989
    targetPort: 5000
  selector:
    app: hello-world-deployment



apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-service-np
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hello-world-service-np-ip
  labels:
    app: hello-world-deployment
spec:
  defaultBackend:
    service:
      name: hello-world-deployment-backend
      port:
        number: 8989



apiVersion: v1
kind: Service
metadata:
  name: hello-world-deployment-backend
  labels:
    app: hello-world-deployment
spec:
  type: NodePort
  selector:
    app: hello-world-deployment
    tier: web
  ports:
  - port: 8989
    targetPort: 5000
