apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-lb
  labels:
    app: hello-world-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8989
    targetPort: 5000
  selector:
    app: hello-world-deployment